server:
    port: 8990
spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: postgres
    password: postdb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format-sql: true
      show-sql: true
  authentication:
    jwt:
      secret: yPTyD4NJtTyXxf9v+Y9bPerZs6XtiCyD+fNdlB/lRmdq4UrpOK6brnicDMZXbgiq
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
storage:
  type: local
  path: uploadFile

